=== mariobacellar/inspector/src/main/resources/dtd/US23770_realizarPreCadastroRequest_out.dtd
<!ELEMENT SiebelMessage (Body) >
<!ATTLIST SiebelMessage MessageId     CDATA #IMPLIED >
<!ATTLIST SiebelMessage MessageType   CDATA #IMPLIED >
<!ATTLIST SiebelMessage IntObjectName CDATA #IMPLIED >
<!ELEMENT Body (realizarPreCadastroRequest+) >
<!ELEMENT realizarPreCadastroRequest (MessageHeader?,ListOfPreCadastro?)>
<!ELEMENT MessageHeader              (Header*) >
<!ELEMENT Header                     (Operation?,TransactionId?,CorrelationId?,BusinessId?,Timestamp?) >
<!ELEMENT ListOfPreCadastro          (PreCadastro*) >
<!ELEMENT PreCadastro                (Cpf?,Email?,NomeCliente?,TipoProduto?,TerminalContrato?,DataVenda?,ContaOnline?,CodSAP?,RazaoSocial?,NomeFantasia?,CanalVendas?,Uf?,Login?) >
<!ELEMENT Operation        (#PCDATA) >
<!ELEMENT TransactionId    (#PCDATA) >
<!ELEMENT CorrelationId    (#PCDATA) >
<!ELEMENT BusinessId       (#PCDATA) >
<!ELEMENT Timestamp        (#PCDATA) >
<!ELEMENT Cpf              (#PCDATA) >
<!ELEMENT Email            (#PCDATA) >
<!ELEMENT NomeCliente      (#PCDATA) >
<!ELEMENT TipoProduto      (#PCDATA) >
<!ELEMENT TerminalContrato (#PCDATA) >
<!ELEMENT DataVenda        (#PCDATA) >
<!ELEMENT ContaOnline      (#PCDATA) >
<!ELEMENT CodSAP           (#PCDATA) >
<!ELEMENT RazaoSocial      (#PCDATA) >
<!ELEMENT NomeFantasia     (#PCDATA) >
<!ELEMENT CanalVendas      (#PCDATA) >
<!ELEMENT Uf               (#PCDATA) >
<!ELEMENT Login            (#PCDATA) >

=== mariobacellar/inspector/src/main/resources/dtd/US23770_realizarPreCadastroRequest_out.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SiebelMessage SYSTEM "US23770_realizarPreCadastroRequest_out.dtd" >
<SiebelMessage IntObjectName="" MessageId="" MessageType="">
  <Body>
    <realizarPreCadastroRequest>
      <MessageHeader>
        <Header>
          <Operation>Operation</Operation>
          <TransactionId>TransactionId</TransactionId>
          <CorrelationId>CorrelationId</CorrelationId>
          <BusinessId>BusinessId</BusinessId>
          <Timestamp>Timestamp</Timestamp>
        </Header>
      </MessageHeader>
      <ListOfPreCadastro>
        <PreCadastro>
          <Cpf>Cpf</Cpf>
          <Email>Email</Email>
          <NomeCliente>NomeCliente</NomeCliente>
          <TipoProduto>TipoProduto</TipoProduto>
          <TerminalContrato>TerminalContrato</TerminalContrato>
          <DataVenda>DataVenda</DataVenda>
          <ContaOnline>ContaOnline</ContaOnline>
          <CodSAP>CodSAP</CodSAP>
          <RazaoSocial>RazaoSocial</RazaoSocial>
          <NomeFantasia>NomeFantasia</NomeFantasia>
          <CanalVendas>CanalVendas</CanalVendas>
          <Uf>Uf</Uf>
          <Login>Login</Login>
        </PreCadastro>
      </ListOfPreCadastro>
    </realizarPreCadastroRequest>
  </Body>
</SiebelMessage>
